[package]
name = "hot-reload-openssl"
version = "0.1.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
description = "Notification-driven OpenSSL credential rotation"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[package.metadata.cargo_check_external_types]
allowed_external_types = ["notify::*", "openssl::*"]

[dependencies]
arc-swap = "1.1"
notify = "8"
openssl = "0.10"

[dev-dependencies]
actix-web = { version = "4.15", features = ["openssl"] }
tempfile = "3"
tokio = { version = "1.38.2", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
