version: "0.2"
words:
  - actix
  - ahash
  - arrayvec
  - bytestring
  - cbor
  - clippy
  - codecov
  - corasick
  - dalek
  - deque
  - deserialization
  - docsrs
  - dtolnay
  - Expiremental
  - hmac
  - hsts
  - indoc
  - ipnetwork
  - itertools
  - memchr
  - memmem
  - msgpack
  - msrv
  - ndjson
  - nextest
  - nixpkgs
  - pemfile
  - pkgs
  - prehashed
  - rdef
  - refcell
  - reqwest
  - robjtede
  - rustdoc
  - RUSTDOCFLAGS
  - rustfmt
  - rustls
  - rustup
  - rustversion
  - serde
  - splitn
  - struct
  - taplo
  - tinyvec
  - trybuild
  - vals
