exclude = ["target/*"]
include = ["**/*.toml"]

[formatting]
column_width = 110

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "dependencies",
  "*-dependencies",
  "workspace.dependencies",
  "workspace.*-dependencies",
  "target.*.dependencies",
  "target.*.*-dependencies",
]
formatting.reorder_keys = true

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "dependencies.*",
  "*-dependencies.*",
  "workspace.dependencies.*",
  "workspace.*-dependencies.*",
  "target.*.dependencies",
  "target.*.*-dependencies",
]
formatting.reorder_keys = false
