name: Set up Nix devshell
description: Install Nix and enter the selected devshell.

inputs:
  devshell:
    description: Flake devshell to enter.
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35

    - name: Enter Nix devshell
      uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
      with:
        arguments: ${{ inputs.devshell }}
