[package]
name = "russe"
version = "0.1.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
description = "Server-Sent Events client"
keywords = ["sse", "server", "sent", "events"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[features]
reqwest-0_12 = []

[dependencies]
aho-corasick = "1"
futures-util = "0.3.18"
tokio = "1"
tokio-util = { version = "0.7", features = ["codec"] }
memchr = "2"

[dev-dependencies]
futures-test = "0.3"
indoc = "2"
tokio = { version = "1.28.2", features = ["macros"] }
tokio-util = { version = "0.7", features = ["codec", "io", "rt"] }

[lints]
workspace = true
