[package]
name = "err-report"
version = "0.0.2"
description = "Clone of the unstable `std::error::Report` type"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]

[dev-dependencies]
indoc = "2"

[lints]
workspace = true
