[package]
name = "err-report"
version = "0.0.1"
description = "Clone of the unstable `std::error::Report` type"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]

[lints]
workspace = true
