[package]
name = "err-report"
version = "0.1.5"
description = "Clone of the unstable `std::error::Report` type"
categories = ["value-formatting", "rust-patterns"]
keywords = ["error", "error-report", "error-chain", "diagnostics"]
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]

[dev-dependencies]
indoc = "2"

[lints]
workspace = true
