name: Coverage

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust
        id: rust
        background: true
        uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        env:
          LD_LIBRARY_PATH: ""
        with:
          components: llvm-tools
          cache-key: ${{ hashFiles('flake.lock') }}

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35

      - name: Enter Nix devshell
        id: devshell
        background: true
        uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1

      - name: Wait for Rust
        wait: rust

      - name: Install just, cargo-llvm-cov
        uses: taiki-e/install-action@4cef1412cce204788f482e778a0b9187f9626a29 # v2.87.21
        env:
          LD_LIBRARY_PATH: ""
        with:
          tool: just,cargo-llvm-cov

      - name: Wait for Nix devshell
        wait: devshell

      - name: Generate code coverage
        run: just test-coverage-codecov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          files: codecov.json
          fail_ci_if_error: true
        env:
          # Use the runner's libraries for Codecov's system tools.
          LD_LIBRARY_PATH: ""
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
